//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace fnaproj {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fnaproj.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using Microsoft.Xna.Framework;
        ///using Microsoft.Xna.Framework.Graphics;
        ///
        ///namespace &lt;namespace&gt;;
        ///
        ///class Game1 : Game
        ///{
        ///
        ///    private SpriteBatch batch;
        ///
        ///
        ///    internal Game1()
        ///    {
        ///        var gdm = new GraphicsDeviceManager(this);
        ///
        ///        gdm.PreferredBackBufferWidth = 1280;
        ///        gdm.PreferredBackBufferHeight = 720;
        ///        gdm.IsFullScreen = false;
        ///        gdm.SynchronizeWithVerticalRetrace = true;
        ///
        ///        Content.RootDirectory = &quot;Content&quot;;
        ///    }
        ///
        ///    protected over [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Game_cs_default {
            get {
                return ResourceManager.GetString("Game.cs.default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///namespace &lt;namespace&gt;;
        ///
        ///public class Game1 : Core
        ///{
        ///    protected override void Initialize()
        ///    {
        ///        base.Initialize();
        ///
        ///        Window.AllowUserResizing = true;
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string Game_cs_nez {
            get {
                return ResourceManager.GetString("Game.cs.nez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///
        ///
        ///#if MONOMAC
        ///using MonoMac.AppKit;
        ///using MonoMac.Foundation;
        ///#elif __IOS__ || __TVOS__
        ///using Foundation;
        ///using UIKit;
        ///#endif
        ///
        ///namespace &lt;namespace&gt;;
        ///
        ///#if __IOS__ || __TVOS__
        ///    [Register(&quot;AppDelegate&quot;)]
        ///    class Program : UIApplicationDelegate
        ///#else
        ///	static class Program
        ///#endif
        ///	{
        ///		private static Game1 _game;
        ///
        ///		internal static void RunGame()
        ///		{
        ///			_game = new Game1();
        ///			_game.Run();
        ///#if !__IOS__ &amp;&amp; !__TVOS__
        ///			_game.Dispose();
        ///#endif
        ///		}
        ///
        ///		/// &lt;summary&gt;        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Program_cs {
            get {
                return ResourceManager.GetString("Program.cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///  &lt;PropertyGroup&gt;
        ///    &lt;OutputType&gt;WinExe&lt;/OutputType&gt;
        ///    &lt;TargetFramework&gt;net8.0&lt;/TargetFramework&gt;
        ///    &lt;ImplicitUsings&gt;enable&lt;/ImplicitUsings&gt;
        ///    &lt;Nullable&gt;enable&lt;/Nullable&gt;
        ///
        ///	&lt;IsWindows Condition=&quot;&apos;$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))&apos; == &apos;true&apos;&quot;&gt;true&lt;/IsWindows&gt; 
        ///	&lt;IsOSX Condition=&quot;&apos;$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.Inter [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string project_csproj {
            get {
                return ResourceManager.GetString("project.csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio Version 17
        ///VisualStudioVersion = 17.0.31903.59
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{9A19103F-16F7-4668-BE54-9A1E7A4F7556}&quot;) = &quot;&lt;project_name&gt;&quot;, &quot;&lt;project_name&gt;\&lt;project_name&gt;.csproj&quot;, &quot;{F5B3B29B-1FF7-4450-8CF2-804111A97F0D}&quot;
        ///EndProject
        ///Project(&quot;{9A19103F-16F7-4668-BE54-9A1E7A4F7556}&quot;) = &quot;FNA.NetStandard&quot;, &quot;FNA\FNA.Core.csproj&quot;, &quot;{08E57E7A-8A48-4B4C-B9FF-90F2750EA16D}&quot;
        ///EndProject
        ///Global
        ///	GlobalSection(Soluti [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string project_sln {
            get {
                return ResourceManager.GetString("project.sln", resourceCulture);
            }
        }
    }
}
